apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-dev
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi