global:
  imageRegistry: "866376286331.dkr.ecr.ap-northeast-2.amazonaws.com"
  imagePullSecrets:
    - name: "registry-local-credential"

# Prometheus Operator 설정
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
    certManager:
      enabled: false
    deployment:
      enabled: false
  # TLS Secret 관련 설정 비활성화 (폐쇄망 환경)
  tls:
    enabled: false
  image:
    repository: prometheus-operator
    tag: v0.67.1
  prometheusConfigReloader:
    image:
      repository: prometheus-config-reloader
      tag: v0.67.1

# Prometheus 서버 설정
prometheus:
  enabled: true
  scrapeconfig:
    enabled: true
  prometheusSpec:
    image:
      repository: prometheus
      tag: v2.46.0
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - prometheus-dev.samsungena.io
    tls:
      - secretName: samsungena.io-tls
        hosts:
          - prometheus-dev.samsungena.io

# AlertManager 설정
alertmanager:
  alertmanagerSpec:
    image:
      repository: alertmanager
      tag: v0.26.0
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - alertmanager-dev.samsungena.io
    tls:
      - secretName: samsungena.io-tls
        hosts:
          - alertmanager-dev.samsungena.io

# Grafana 설정
grafana:
  enabled: true
  image:
    repository: grafana
    tag: 10.1.0
  adminPassword: admin123!
  initChownData:
    enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  operator:
    enabled: false
    dashboardsConfigMapRefEnabled: false
  persistence:
    enabled: true
    storageClassName: gp2
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana-dev.samsungena.io
    tls:
      - secretName: samsungena.io-tls
        hosts:
          - grafana-dev.samsungena.io

# Node Exporter 설정
prometheus-node-exporter:
  image:
    repository: node-exporter
    tag: v1.6.1

# Node Exporter 운영체제 설정
nodeExporter:
  operatingSystems:
    linux:
      enabled: true
    darwin:
      enabled: false
    aix:
      enabled: false

# Kube State Metrics 설정
kube-state-metrics:
  image:
    repository: kube-state-metrics
    tag: v2.10.0
  prometheus:
    scrapeconfig:
      enabled: false