#!/bin/bash

# GitHub Issue 생성 및 프로젝트 백로그 자동 등록 스크립트
# Usage: ./create_issue_and_backlog.sh "Title" "Body" "label1,label2"

set -e

TITLE="$1"
BODY="$2"
LABELS="$3"
PROJECT_ID="2"  # helm chart project ID
OWNER="sirosms"

if [[ -z "$TITLE" ]]; then
    echo "Usage: $0 'Issue Title' 'Issue Body' 'label1,label2'"
    exit 1
fi

# Default body if not provided
if [[ -z "$BODY" ]]; then
    BODY="🤖 Auto-generated issue from deployment script

## Summary
An error or task was detected during deployment/operation.

## Generated by
Claude Code automation

🤖 Generated with [Claude Code](https://claude.ai/code)"
fi

# Default label
if [[ -z "$LABELS" ]]; then
    LABELS="enhancement"
fi

echo "Creating GitHub issue..."

# Create issue and capture URL
ISSUE_URL=$(gh issue create \
    --title "$TITLE" \
    --body "$BODY" \
    --label "$LABELS" \
    --repo "${OWNER}/k8s-helm")

if [[ $? -eq 0 ]]; then
    echo "✅ Issue created: $ISSUE_URL"
    
    # Add to project backlog
    echo "Adding to project backlog..."
    gh project item-add --owner "$OWNER" "$PROJECT_ID" --url "$ISSUE_URL"
    
    if [[ $? -eq 0 ]]; then
        echo "✅ Added to project backlog successfully!"
        echo "🔗 Project: https://github.com/users/${OWNER}/projects/${PROJECT_ID}"
    else
        echo "❌ Failed to add to project backlog"
    fi
else
    echo "❌ Failed to create issue"
    exit 1
fi