{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $pathType := .Values.ingress.pathType -}}
{{- $usePathType := semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.ingress.servicePort -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
          {{- if $usePathType }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
        {{- range .Values.ingress.addPaths }}
          - path: {{ .path }}
          {{- if $usePathType }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .servicePort }}
          {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort }}
          {{- end }}
        {{- end }}
  {{- range .Values.ingress.addHosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
          {{- if $usePathType }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
  {{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- range .Values.ingress.addHosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ include "app.tlsSecretName" . }}
{{- end }}
{{- end }}
