{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.roleBindingKind }}
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.roleRef.kind }}
  name: {{ .Values.rbac.roleRef.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}